name: "Railway PR Deploy Action"
description: "Creates an environment with provided environment variables and deploys them to Railway."
inputs:
    RAILWAY_API_TOKEN: # railway token
        description: "Railway API Token"
        required: true
    PROJECT_ID:
        description: "The id of the project to create environments on. Can be found on Settings -> General page"
        required: true
    SRC_ENVIRONMENT_NAME:
        description: "The name of the environment to base the PRs off of. "
        required: true
    SRC_ENVIRONMENT_ID:
        description: "The id of the environment to base the PRs off of. If this is provided, SRC_ENVIRONMENT_NAME will be ignored. "
        required: false
    DEST_ENV_NAME:
        description: "The name of the deployed PR environment. Usually a combination of pr-<PR_NUMBER>-<SHORT_COMMIT_HASH> passed inside of workflow"
        required: true
    FAIL_IF_EXISTS:
      description: "Whether to fail the action if the destination environment already exists. Set to `false` to re-use existing environment"
      default: "true"
      required: false
    ENV_VARS:
        description: 'The environment variables to set on the PR environment. Should be a JSON object of key value pairs. e.g. {"DATABASE_URL": "test_url", "A": "abc", "D": "efg"}'
        default: '{}'
        required: false
    API_SERVICE_NAME:
        description: "The name of the API service to use for the PR environment. This is used to identify the domain of the deployed PR environment."
        required: false
    IGNORE_SERVICE_REDEPLOY:
        description: "A list of service names to ignore when redeploying the PR environment. This is useful for services that don't need to be redeployed on every PR deployment."
        default: '[]'
        required: false
outputs:
    service_domain:
        description: "The domain of the deployed PR environment"
runs:
    using: "node20"
    main: "dist/index.cjs"
